variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  token: 6jd5PyyLxwV8wwRP1YTB

image: maven:3.8.5-openjdk-17

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target
    - javadoc

build_job:
  stage: build
  tags:
    - docker

  script:
    - echo "Maven compile started"
    - "mvn compile -B"
    - echo $SOME_VARIABLE

test_job:
  stage: test
  tags:
    - docker

  script: 
    - echo "maven test started"
    - "mvn clean test -B"
    - echo $SOME_VARIABLE


package_job:
  stage: package
  tags:
    - docker

  script:
    - echo "Maven packaging started"
    - "mvn package -B"
    - echo $SOME_VARIABLE

javadoc_job:
  stage: build
  tags:
    - docker

  script:
    - echo "Generating Javadoc"
    - export ACCESS_TOKEN=$CI_CD  # Set the access token as an environment variable
    - mvn javadoc:javadoc
  artifacts:
    paths:
      - javadoc/apidocs/*






