variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  CI_SERVER_URL: https://git.gvk.idi.ntnu.no/course/idatg2001/idatg2001-2023-ws/eskal/mappeoppgaveidatg2001
  CI_JOB_TOKEN: 5YF8D2CFF

image: maven:3.8.5-openjdk-17

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target
    - javadoc

build_job:
  stage: build
  tags:
    - docker

  script:
    - echo "Maven compile started"
    - "mvn compile -B"
    - echo $SOME_VARIABLE

test_job:
  stage: test
  tags:
    - docker

  script: 
    - echo "maven test started"
    - "mvn clean test -B"
    - echo $SOME_VARIABLE


package_job:
  stage: package
  tags:
    - docker

  script:
    - echo "Maven packaging started"
    - "mvn package -B"
    - echo $SOME_VARIABLE

pages:
  stage: deploy
  tags:
    - docker
  script:
    - mkdir .public
    - cp -r javadoc/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main




