variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
image: maven:3.8.5-openjdk-17

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target
    - javadoc

build_job:
  stage: build
  tags:
    - docker

  script:
    - echo "Maven compile started"
    - "mvn compile -B"
    - echo $SOME_VARIABLE

test_job:
  stage: test
  tags:
    - docker

  script: 
    - echo "maven test started"
    - "mvn clean test -B"
    - echo $SOME_VARIABLE


package_job:
  stage: package
  tags:
    - docker

  script:
    - echo "Maven packaging started"
    - "mvn package -B"
    - echo $SOME_VARIABLE

pages:
  stage: deploy
  tags:
    - docker
  when: manual

  script:
    - mvn javadoc:javadoc
    - mv target/site/apidocs/ ./
    - git config user.email "eskilal@stud.ntnu.no"
    - git config user.name "eskilal"
    - git add apidocs
    - git commit -m "Update JavaDoc"
    - git push https://git.gvk.idi.ntnu.no/course/idatg2001/idatg2001-2023-ws/eslatte/mappevudering-idatg2001-gruppe-3.git HEAD:main
  only:
    - main





