variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:3.8.5-openjdk-17

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target
    - javadoc

build_job:
  stage: build
  tags:
    - docker

  script:
    - echo "Maven compile started"
    - "mvn compile -B"
    - "mvn javadoc:javadoc"
    - echo $SOME_VARIABLE
  artifacts:
    paths:
      - target
      - javadoc


test_job:
  stage: test
  tags:
    - docker

  script: 
    - echo "maven test started"
    - "mvn clean test -B"
    - echo $SOME_VARIABLE


package_job:
  stage: package
  tags:
    - docker

  script:
    - echo "Maven packaging started"
    - "mvn package -B"
    - echo $SOME_VARIABLE

deploy:
  stage: deploy
  script:
    - mv public public_old || true
    - mkdir public
    - mv javadoc/* public/
  artifacts:
    paths:
      - public
  only:
    - main
