variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:3.8.3-openjdk-17

stages:
  - build
  - test
  - package 

build_job:
    stage: build
    tags:
       - docker

    script:
        - echo "Maven compile started"
        - "mvn compile"

test_job:
    stage: test
    tags:
        - docker

    script:
        - echo "Maven test Started"
        - "mvn test"

package_job:
    stage: package
    tags:
        - docker 

    script:
        - echo "Maven package started"
        - "mvn package"


